import type { FinancialRecord } from "./types";

/**
 * Mock financial records. Replace with a real API + S3-backed file store
 * once the backend exists (see Context_Instruction.md §3/§8).
 */
export const MOCK_FINANCIAL_RECORDS: FinancialRecord[] = [
  {
    id: "fin-1",
    title: "July 2026 Revenue Summary",
    category: "Revenue",
    periodMonth: 7,
    periodYear: 2026,
    notes: "Includes Rome and Tuscany portfolios.",
    fileName: "revenue-2026-07.xlsx",
    fileSize: "62 KB",
    uploadedBy: "Martina Vance",
    uploadedAt: "2026-08-02",
    tagUserId: "2",
    tagUserName: "Giulia Romano",
    tagUserRole: "owner",
  },
  {
    id: "fin-2",
    title: "July 2026 Owner Payouts",
    category: "Payouts",
    periodMonth: 7,
    periodYear: 2026,
    notes: "",
    fileName: "payouts-2026-07.xlsx",
    fileSize: "44 KB",
    uploadedBy: "Martina Vance",
    uploadedAt: "2026-08-03",
    tagUserId: "9",
    tagUserName: "Alessandro Barbieri",
    tagUserRole: "owner",
  },
  {
    id: "fin-3",
    title: "Q2 2026 Operating Expenses",
    category: "Expenses",
    periodMonth: 6,
    periodYear: 2026,
    notes: "Cleaning, maintenance, and concierge costs.",
    fileName: "expenses-q2-2026.csv",
    fileSize: "18 KB",
    uploadedBy: "Valentina Greco",
    uploadedAt: "2026-07-10",
    tagUserId: "",
    tagUserName: "",
    tagUserRole: "",
  },
  {
    id: "fin-4",
    title: "2025 Annual Tax Filing",
    category: "Taxes",
    periodMonth: 12,
    periodYear: 2025,
    notes: "Filed with accountant; final copy.",
    fileName: "tax-filing-2025.xlsx",
    fileSize: "128 KB",
    uploadedBy: "Martina Vance",
    uploadedAt: "2026-01-28",
    tagUserId: "",
    tagUserName: "",
    tagUserRole: "",
  },
  {
    id: "fin-5",
    title: "June 2026 Revenue Summary",
    category: "Revenue",
    periodMonth: 6,
    periodYear: 2026,
    notes: "",
    fileName: "revenue-2026-06.xlsx",
    fileSize: "58 KB",
    uploadedBy: "Martina Vance",
    uploadedAt: "2026-07-02",
    tagUserId: "3",
    tagUserName: "Marco Bianchi",
    tagUserRole: "agent",
  },
  {
    id: "fin-6",
    title: "Miscellaneous Reconciliations",
    category: "Other",
    periodMonth: 5,
    periodYear: 2026,
    notes: "Bank reconciliation working file.",
    fileName: "reconciliations-2026-05.xls",
    fileSize: "35 KB",
    uploadedBy: "Valentina Greco",
    uploadedAt: "2026-06-15",
    tagUserId: "7",
    tagUserName: "Davide Moretti",
    tagUserRole: "agent",
  },
];
